parent(tom,bob).
parent(pam,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(pat,jim).
male(tom).
male(jim).
male(bob).
female(liz).
female(ann).
female(pat).
diff(X,Y):-not(X=Y).
father(X,Y):-male(X),parent(X,Y).
offspring(X,Y):-parent(Y,X).
mother(X,Y):-female(X),parent(X,Y).
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
sister(X,Y):-female(X),parent(Z,X),parent(Z,Y),diff(X,Y).
bro(X,Y):-male(X),parent(Z,X),parent(Z,Y),diff(X,Y).
aunt(X,Y):-parent(Z,Y),sister(X,Z).
haschild(X):-parent(X,Z).
greatgrandparent(X,Y):-father(X,Z),grandparent(Z,Y).
uncle(X,Y):-parent(Z,Y),bro(X,Z).
predecessor(X,Y):-parent(X,Y).
predecessor(X,Y):-parent(Z,Y),predecessor(X,Z).

