parent(pam,bob).
parent(tom,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(pat,jim).
female(pam).
female(liz).
female(pat).
female(ann).
male(tom).
male(bob).
male(jim).
father(X,Y):-parent(X,Y),male(X).
mother(X,Y):-parent(X,Y),female(X).
gparent(X,Y):-parent(X,Z),parent(Z,Y).
offspring(Y,X):-parent(X,Y).
sister(X,Y):-parent(Z,X),parent(Z,Y),not(X==Y),female(X),female(Y).
